/// Directories skipped by the file walker (shouldIgnore in process.zig).
/// The watcher skips the same dirs so their writes never enter the OS event queue.
/// Matching is substring-based (path-contains).
pub const DEFAULT_SKIP_DIRS = [_][]const u8{
    "node_modules",
    "bower_components",
    ".git",
    ".svn",
    ".hg",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".tox",
    ".venv",
    "venv",
    ".eggs",
    ".hypothesis",
    "target",
    "build",
    "dist",
    "vendor",
    "coverage",
    ".nyc_output",
    ".idea",
    ".vscode",
    ".DS_Store",
    ".cache",
    ".zig-cache",
    ".gradle",
    ".terraform",
    ".bundle",
    ".turbo",
    ".nx",
    ".parcel-cache",
    ".next",
    ".nuxt",
    ".svelte-kit",
    ".angular",
    ".astro",
    ".docusaurus",
    ".expo",
    ".yarn",
    ".pnpm-store",
    ".vercel",
    ".netlify",
    "zig.conf.json",
};
