export const VIRT_LINE_THRESHOLD = 500;
export const VIRT_BYTE_THRESHOLD = 200 * 1024; // 200 KB
export const VIEWER_LINE_HEIGHT = 20; // px — must match CSS .vline height
export const VIEWER_OVERSCAN = 15;
export const HL_CHUNK_SIZE = 200;

export const PRISM_MAP: Record<string, string> = {
    zig: "zig",
    js: "javascript",
    javascript: "javascript",
    mjs: "javascript",
    cjs: "javascript",
    jsx: "jsx",
    lua: "lua",
    ts: "typescript",
    typescript: "typescript",
    tsx: "tsx",
    json: "json",
    html: "markup",
    htm: "markup",
    xml: "markup",
    svg: "markup",
    vue: "markup",
    svelte: "markup",
    astro: "markup",
    css: "css",
    scss: "scss",
    less: "less",
    bash: "bash",
    sh: "bash",
    zsh: "bash",
    c: "c",
    h: "c",
    cpp: "cpp",
    hpp: "cpp",
    cc: "cpp",
    cxx: "cpp",
    hh: "cpp",
    rs: "rust",
    go: "go",
    mod: "go",
    py: "python",
    pyw: "python",
    pyi: "python",
    rb: "ruby",
    java: "java",
    kt: "kotlin",
    kts: "kotlin",
    groovy: "groovy",
    scala: "scala",
    cs: "csharp",
    fs: "fsharp",
    vb: "vbnet",
    php: "php",
    swift: "swift",
    dart: "dart",
    jl: "julia",
    hs: "haskell",
    elm: "elm",
    clj: "clojure",
    ex: "elixir",
    exs: "elixir",
    erl: "erlang",
    md: "markdown",
    toml: "toml",
    yaml: "yaml",
    yml: "yaml",
    sql: "sql",
};
