//! Chunked LLM report: streams the document through a ChunkWriter, rotating to a
//! new chunk at the configured byte budget and re-emitting a continuation header
//! each time so every chunk is self-describing.

const std = @import("std");
const Config = @import("../../../config/Config.zig");
const ReportData = @import("../aggregator.zig").ReportData;
const Analysis = @import("Analysis.zig");
const sections = @import("sections.zig");
const ChunkWriter = @import("ChunkWriter.zig");
const VERSION = @import("../../../config/Config.zig").VERSION;

pub fn write(
    io: std.Io,
    data: *const ReportData,
    analysis: *const Analysis,
    binary_count: usize,
    llm_path: []const u8,
    root_path: []const u8,
    cfg: *const Config,
    chunk_size: usize,
    allocator: std.mem.Allocator,
) !void {
    const base_path = if (std.mem.endsWith(u8, llm_path, ".md"))
        llm_path[0 .. llm_path.len - 3]
    else
        llm_path;

    var cw = try ChunkWriter.init(io, base_path, root_path, chunk_size, allocator);
    defer cw.deinit();

    // header + description + stats + Source heading.
    {
        var pw: std.Io.Writer.Allocating = .init(allocator);
        defer pw.deinit();
        const w = &pw.writer;
        try w.print("# Project: {s}\nGenerated by zigzag {s} at {s}\n\n", .{ root_path, VERSION, data.date_str });
        try sections.writeDescription(w, cfg);
        try sections.writeStatistics(w, analysis, binary_count);
        try w.writeAll("## Source\n\n");
        try cw.writeRaw(pw.written());
    }

    for (analysis.real_entries.items, analysis.file_contents.items) |entry, fc| {
        var fw: std.Io.Writer.Allocating = .init(allocator);
        defer fw.deinit();
        try sections.writeSourceBlock(&fw.writer, entry, fc, cfg.llm_signatures);
        const block = fw.written();

        // Keep each file's block whole
        if (cw.current_bytes > 0 and cw.current_bytes + block.len > chunk_size) {
            try cw.rotateChunk();
            const cont_hdr = try std.fmt.allocPrint(allocator, "# Project: {s} (continued — chunk {d})\n\n## Source\n\n", .{ root_path, cw.chunk_index });
            defer allocator.free(cont_hdr);
            try cw.writeRaw(cont_hdr);
            try cw.writeRaw(block);
            try cw.addCurrentFile(entry.path);
        } else {
            try cw.writeFile(entry.path, block);
        }
    }

    try cw.finalize();
}
